### ISSUE TITLE
Hi Kovid

### ISSUE THREAD

**Issue by artyprog** [kovidgoyal/rapydscript-ng#14]
In web browse compiler
I encounter a problem with list comprehension
lst = [x fof x in range(5)]
I get

ReferenceError: Symbol is not defined

Regards

**Comment by kovidgoyal** [comment]
You need to use a modern browser (one that supports ES 6) as is noted in the readme in that section.

**Comment by artyprog** [comment]
Ok thanks Kovid

**Comment by v3ss0n** [comment]
we can also cross compile using babeljs .

**Comment by kovidgoyal** [comment]
Cross compiling with Babel will not help, as the problem is not outputting ES 5 code, it is adding code to the exported compiler to cross compile, which increases the size of the compiler from 600KB to 6MB.

Technically, you can make make rapydscript-ng itself output an ES 5 compatible REPL, just change js_version in tools/embedded_compiler.js to 5 and run bin/web-repl-export
