### ISSUE TITLE
typy(object) unexpected

### ISSUE THREAD

**Issue by BruceSherwood** [kovidgoyal/rapydscript-ng#140]
In CPython, a = {'a':'cat'}; print(type(a)) yields <type 'dict'> but in RapydScript it yields function Object() { [native code] }. I don't understand the value in returning a function rather than a name (such as object.constructor.name). I understand the complexities of returning what Python would return, but wouldn't something like <class 'object'> make more sense than the code for that object?

**Comment by BruceSherwood** [comment]
A somewhat related issue: isinstance works with some objects, but isinstance(5,xxx) is False for all the values of xxx that I can think of trying.

**Comment by BruceSherwood** [comment]
And just in case it might be useful to you, I've found the following scrap very useful:

// Angus Croll:
// http://javascriptweblog.wordpress.com/2011/08/08/fixing-the-javascript-typeof-operator/
// {...} "object"; [...] "array"; new Date "date"; /.../ "regexp"; Math "math"; JSON "json";
// Number "number"; String "string"; Boolean "boolean"; new ReferenceError) "error"

var toType = function(obj) { 
	return ({}).toString.call(obj).match(/\s([a-zA-Z]+)/)[1].toLowerCase()
}

**Comment by kovidgoyal** [comment]
type() returns the type object for the passed in instance. In JavaScript types are Objects which is why you get an Object returned. What you see is simply the string representation of the Object constructor, the type() function has no influence on that. To fix this would require changing the toString() implementation of every Object, which could break interop with other JS code, so I am not going to do that.

And in JS, therefore also RS there is only a single numeric type, no separate integers/floats. You can test if something is a number with jstype(x) is 'number'

**Comment by BruceSherwood** [comment]
Okay. I solved my problem by creating a pytype() function (using the toType machinery) and redefining type = pytype. The reason I wanted to return a string that looks like what CPython returns is that I try to make VPython programs run without change in both the pure browser version (at glowscript.org) and with installed Python.

**Comment by kovidgoyal** [comment]
type() does not return a string in python either, FYI.

**Comment by BruceSherwood** [comment]
That is amusing. I see that its type is <class 'type'>. Thanks for the tip.
