### ISSUE TITLE
bitops on booleans

### ISSUE THREAD

**Issue by jayvdb** [kovidgoyal/rapydscript-ng#165]
For input
```py
def main_func():
    ands = []
    ors = []
    xors = []
    for a in [False, True]:
        for b in [False, True]:
            ands.append(a & b)
            ors.append(a | b)
            xors.append(a ^ b)
    assert ands == [False, False, False, True]
    assert ors == [False, True, True, True]
    assert xors == [False, True, True, False]
    print("OK")

if __name__ == "__main__":
    main_func()
```

The JS transpiled version fails with
```node

/private/tmp/unparse.js:4392
            if (!(ρσ_equals(ands, ρσ_list_decorate([ false, false, false, true ])))) throw new AssertionError;
                                                                                     ^
Error
    at AssertionError.__init__ (/private/tmp/unparse.js:2224:19)
    at AssertionError.__init__ (/private/tmp/unparse.js:2347:66)
    at new AssertionError (/private/tmp/unparse.js:2343:39)
    at main_func (/private/tmp/unparse.js:4392:92)
    at /private/tmp/unparse.js:4405:13
    at /private/tmp/unparse.js:4407:7
    at Object.<anonymous> (/private/tmp/unparse.js:4408:3)
    at Module._compile (node:internal/modules/cjs/loader:1109:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1138:10)
    at Module.load (node:internal/modules/cjs/loader:989:32) {
  message: undefined
}
```

The JS `ands` contains `[0, 0, 0, 1]`.

This is one of the test cases of https://github.com/adsharma/py2many .  As a result, it is a bit contrived.  I've read https://github.com/kovidgoyal/rapydscript-ng/issues/38 and can understand/accept the decision there, if you feel it also applies here.

**Comment by kovidgoyal** [comment]
I think the issue is the same. There is no way to have 

```
bool bitwise-op bool
```

return a bool instead of a number in rapydscript other than overloading
the bitwise operators or special casing the JS generated for those
operators. Both harm performance, for obvious reasons. 

In JavaScript bitwise operators on booleans return numbers, dont ask me
why. While it is possible to workaround that in RapydScript doing so
would entail slowing down the bitwise operators everywhere. Not a
worthwhile tradeoff, IMO.
