### ISSUE TITLE
static member variables referenced inconsistantly

### ISSUE THREAD

**Issue by courtc** [kovidgoyal/rapydscript-ng#20]
Static variables don't quite work properly, unless they are a function.

This works:
```python
class Foo:
    value = def(): return 1
print(Foo.value())
```
```javascript
[...]
Foo.prototype.value = function () {
    return 1;
};
print(Foo.prototype.value.call());
```
While a non-function does not:
```python
class Foo:
    value = 1
print(Foo.value)
```
```javascript
[...]
Foo.prototype.value = 1;
print(Foo.value);
```

**Comment by kovidgoyal** [comment]
Class variables are not currently automatically recognized -- You have to do Foo.prototype.varname instead of just Foo.varname.

Having the compiler recognize class variables is not too hard, just not something I have gotten around to as yet, as I personally dont use class variables very often in my code.

**Comment by courtc** [comment]
Right, I have been using the Foo.prototype.varname syntax to workaround the issue.

It's certainly not a critical issue for me, I just thought I'd log it here.
