### ISSUE TITLE
The 'new' keyword isn't always put in front of class instantiation

### ISSUE THREAD

**Issue by feihong** [kovidgoyal/rapydscript-ng#37]
Here's an example program that illustrates the problem:

```python
def oh_no():
    robot = Robot()

class Robot:
    pass
```

In the generated JavaScript, this is what oh_no() looks like:

```javascript
function oh_no() {
    var robot;
    robot = Robot();
};
```

If the oh_no() function is put after the class definition, it does work. However, this behavior is not intuitive for people used to Python.

**Comment by kovidgoyal** [comment]
class detection is very much a best effort thing. There are many ways to fool it, for example:

```py
class A:
    pass

def b():
   pass

def a():
    A = b
    return A()
```

RS will incorrectly put a new in the return statement. Or you can pass classes as function arguments, in which case RS has no way to know the function argument is a class. 

Some of these issues, local variable shadowing, use before declaration, etc. could be solved by making the compiler smarter, but since this requires fairly invasive changes to the compiler and can never be made 100% bulletproof, it is not a priority for me, patches are welcome.

**Comment by feihong** [comment]
Yes, I now see how this is a fairly difficult issue to deal with. I guess my only suggestion is that if people keep running into this issue, there should be a note added to the documentation. By the way, thanks for your hard work on this project!

**Comment by kovidgoyal** [comment]
There is already a note about it in the gotchas section of the readme, if you feel the wording can be improved, feel free to send a PR.

**Comment by feihong** [comment]
I re-read the relevant sections of the README, and it's actually even more clear in the "External Classes" section:

> RapydScript will automatically detect classes declared within the same scope (as long as the declaration occurs before use)...

So I feel you've already adequately covered it, but it's on users to read and absorb it all ;-)
