### ISSUE TITLE
max(list)?

### ISSUE THREAD

**Issue by BruceSherwood** [kovidgoyal/rapydscript-ng#60]
The RS-NG doc implies that lists have nearly all the properties of Python lists, so I'm surprised that max([5,2,3]) gives undefined.

**Comment by BruceSherwood** [comment]
Thanks much, Kovid. You might like to know that there are now just over 20,000 registered users at glowscript.org. I don't have data on how many of them are active users, but clearly your RS-NG is benefiting a lot of people, many of them students. The questions about range and list reflect the fact that with an expanding number of users there is an expanding exploration of the RS-NG space.

**Comment by kovidgoyal** [comment]
Good to know :)

**Comment by icarito** [comment]
I just released Jappy Activity, a Python coding environment for Sugar and Sugarizer, powered by RapydScript-ng. Hopefully children will start learning also! Thanks for your support! Thanks also @BruceSherwood for the inspiration!

**Comment by kovidgoyal** [comment]
Cool -- I have actually always intended to use rs-ng to teach my own children to programonce they are old enough. What is sugar? Can you post a link?

**Comment by BruceSherwood** [comment]
trinket.io makes it easy to place in a web page, side by side, editing and execution of GlowScript VPython, which sounds a bit like Jappy (https://wiki.sugarlabs.org/go/Project/Develop_Activity). Rhett Allain in his physics blog for Wired magazine has shown examples of this:

https://www.wired.com/2015/04/dare-change-numerical-calculation

**Comment by icarito** [comment]
@kovidgoyal Great to hear we have similar goals! My eldest (6yo) is about to get there shortly. Currently I just started her with some block-based puzzles (from robotopia.co - good inspiration for building something for them). [Sugar](http://www.sugarlabs.org/) is a Desktop Environment for GNU/Linux (they don't call it a Desktop, but a Constructionist Learning Environment). It was designed for primary school children who got OLPC XO laptops, but since then it has been packaged for most GNU/Linux distributions. It is mostly written in Python. It has an interesting software collection (e.g. Turtle Blocks). It has not had the traction it envisioned but many of us still believe in the basic premise of a simplified, no-ceiling design. Since a couple of years there has been an effort to port many of the same concepts over to an HTML5 environment called [Sugarizer](http://try.sugarizer.org/), meant to mimic the experience on the Web, Android, etc. It's not quite the same but it will give you an idea. There's even a version that replaces the Android Home app (that's what my kids have been using thus far).

I wrote *Jappy* activity to closely mimic *[Pippy](https://wiki.sugarlabs.org/go/Activities/Pippy)* activity, so that it may be adopted and bundled with Sugarizer, offer a familiar environment to people already using Pippy, and a solid base to build an improved experience.

@BruceSherwood thanks for the reference. I was aware of Trinket but hadn't seen the Glowscript version. Jappy has a different usage in mind, as it is meant to be able to be used offline as a standalone application (or bundled in Sugarizer). It is itself written in Rapydscript, and I hope it will become my own IDE of choice when it is more capable, at least for this type of coding. By the way, thanks for finding and sharing the link to Jappy! I was sure I'd done that myself.

**Comment by kovidgoyal** [comment]
Ah, thanks! I remember the OLPC project sending me a prototype many years ago to see about porting calibre to it -- but unfortunately it never went anywhere. 

My 5yr old currently programs using the venerable logo programming language, but as her reading comprehension is improving I am looking to move her to a "real" programming language.
