### ISSUE TITLE
extra code in function def

### ISSUE THREAD

**Issue by valq7711** [kovidgoyal/rapydscript-ng#78]
## functions.pyj:
`function_definition` and `function_annotation` produce extra code (wrappers and obj.defProp) ,  because `self.argnames.length` is always `> 1` for the class not-static methods.   
Expected  something like:
```
self.argnames.length and self.argnames[0].name is not "self" or self.argnames.length > 1
```
regards

**Comment by kovidgoyal** [comment]
I dont understand what you are saying. There is no ``self.argnames``. There is an ``__argnames__`` but it is a map and has no length. Do you mean ``arguments``? If so self is not included in it. In JS self is this for bound methods.

**Comment by valq7711** [comment]
Wow!  Look at [`this` ](https://github.com/kovidgoyal/rapydscript-ng/blob/3050f51f7c5cbb122e609749ca7ad5d95a51f6dc/src/output/functions.pyj#L151).

**Comment by kovidgoyal** [comment]
Ah you mean the compiler code rather than the generated code. The wrapper is needed to create ``__argnames__`` which is used when functions are *called* with keyword arguments. Therefore, they must be there for all functions that take arguments. Remember that class methods can be called both bound and un-bound and in the latter case, self is a normal argument. Although to be fair, I dont recall if calling an unbound method with self=x actually works in rs-ng.

Not to mention that your proposed fix would break any function that simply used self as an argument name, even if it is not a class method.

**Comment by kovidgoyal** [comment]
The correct fix for an empty ``__argnames__`` is https://github.com/kovidgoyal/rapydscript-ng/commits/master

**Comment by valq7711** [comment]
Could you explain more, because the following:
```
class Foo:
    def bar():
        pass
```
turns into
```
...
if (!Foo.prototype.bar.__argnames__) Object.defineProperties(Foo.prototype.bar, {
    __argnames__ : {value: []}
});
...
```
so, what is it for?

**Comment by kovidgoyal** [comment]
It's not needed, I just misunderstood what you were saying. It is needed only if there are arguments in addition to self. See the commit I linked to earlier.

**Comment by valq7711** [comment]
Excellent, but that's not enough, because the method can be decorated;)

**Comment by kovidgoyal** [comment]
What does decoration have to do with it?

**Comment by valq7711** [comment]
```
@qq
def ee(self):
    pass
```
=>
```
A.prototype.ee = qq((function() {
    var ρσ_anonfunc = function ee() {
        var self = this;
    };
    if (!ρσ_anonfunc.__argnames__) Object.defineProperties(ρσ_anonfunc, {
        __argnames__ : {value: []}
    });
    return ρσ_anonfunc;
})());
```

 [should be fixed like previous one](https://github.com/kovidgoyal/rapydscript-ng/blob/c0a49d09a8e23c58353397e1d19cf63536e7f5b8/src/output/functions.pyj#L187)

**Comment by valq7711** [comment]
As you can see, the decorator produce dummy wrapper, doesn't it?

**Comment by kovidgoyal** [comment]
Already fixed.
