### ISSUE TITLE
Overloading measurement

### ISSUE THREAD

**Issue by BruceSherwood** [kovidgoyal/rapydscript-ng#81]
Kovid, I looked again at the issue someone raised about the possibility of handling operator overloading in RS-NG. I've just remeasured much more carefully the execution speed for a = b+c with and without the operator overloading I use in GlowScript. My test consists of 25 repetitions of the following code, with the 50 statements in a JS for loop, with the statements designed to ensure that JS is unlikely to be able to optimize:

```
        x = x["+"](y);
        y = x["+"](y);
```
        
x and y were integers or floating-point numbers. I made the same measures with this pattern:

```
        x = x+y;
        y = x+y;
```
        
I found essentially no difference in the execution speed in the two cases. In both cases a single statement takes about 12 nanoseconds on my Windows desktop machine. In the overloading case the execution drives this:

`Number.prototype['+'] = function (r) { return this + r }`

If x and y are vectors, this is what is triggered:

`vec.prototype['+'] = vec.prototype.add`

I realize that my situation is a particularly simple one, namely that there are really only two variable types, Number and vec, and I can't picture what difficulties you would face in making Python operator overloading work in RS-NG. But I thought I should report that I'm paying a negligible cost in execution speed, which I hadn't fully realized.

**Comment by kovidgoyal** [comment]
Actual operator overloading is much more complex than that and pays a much higher penalty. For instance, the JS for proper overloading would need to be

x + y becomes rapydscript_add(x, y)

where rapydscript_add is implemented something like

```js
if (typeof x.__add__ === 'function') return x.__add__(y);
return x + y;
```

And in the actual __add__ function you will have to do both type checking and actual addition. And  the runtime will have to deal witht he possibility of __add__ raising exceptions because of the type checking.
